---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/chiggs/docker/volumes/sonarr:/config
      - /plexdrive:/mnt/media
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/chiggs/docker/volumes/radarr:/config
      - /plexdrive:/mnt/media
    ports:
      - 7878:7878
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/chiggs/docker/volumes/bazarr:/config
      - /plexdrive/media/movies:/movies #optional
      - /plexdrive/media/television:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/chiggs/docker/prowlarr/:/config
      - /plexdrive/downloads/torrents/:/mnt/media/torrents
      - /plexdrive/downloads/usenet/:/mnt/media/usenet
    ports:
      - 9696:9696
    restart: unless-stopped
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/chiggs/docker/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped