---
version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/chiggs/docker/volumes/homeassistant:/config
#    ports:
#      - 8123:8123 #optional
    # devices:
    #   - /path/to/device:/path/to/device #optional
    restart: unless-stopped
  grocy:
    image: lscr.io/linuxserver/grocy
    container_name: grocy
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=America/New_York
    volumes:
      - /home/chiggs/docker/volumes/grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped
